### ISSUE TITLE
Purple-Black Textures on map icons

### ISSUE THREAD

**Issue by SupinePandora43** [Nak2/StormFox#10]
in my gmod, lot of maps without icon. And in game i see translucent, but in StormFox i see Purple-Black icons!!!

**Comment by Nak2** [comment]
I'm just loading the map-icons from your client. StormFox does not add or remove map-icons.

**Comment by SupinePandora43** [comment]
StormFox not remove map icons from game menu! and lot of my maps use default translucent map icon(in gamemenu). but stormFox in (where can see what map scanned,has env_....) for maps without icon use purple-black texture

**Comment by SupinePandora43** [comment]
StormFox support temperature changing only for 1 player? if yes, can be realized warm temperature in vehicle!
