### ISSUE TITLE
Lightmaps are not updating correctly

### ISSUE THREAD

**Issue by UAVXP** [Nak2/StormFox#11]
Video can describe this issue better: [YouTube](https://youtu.be/AuKJW7yl5D0)
This video contains showing all the settings, the issue and also my addon list.
Captured on the listen (P2P-off) server

Here are all the console variables of StormFox at the moment of video recording:
"sf_enablespooky" = "1"
"sf_enable_breath" = "1"
"sf_useAInode" = "1"
"sf_renderscreenspace_effects" = "1"
"sf_allow_raindrops" = "1"
"sf_redownloadlightmaps" = "1"
"sf_dynamiclightamount" = "5.000000" ( def. "0" )
"sf_allow_dynamicshadow" = "1" ( def. "0" )
"sf_allow_sunbeams" = "1"
"sf_allow_dynamiclights" = "1"
"sf_allow_windsound" = "1"
"sf_allow_rainsound" = "1"
"sf_material_replacment" = "1"
"sf_exspensive" = "20" ( def. "0" )
"sf_disableeffects" = "0"
"sf_foliagesway" = "1"
"sf_realtime" = "0"
"sf_block_lightenvdelete" = "1"
"sf_autoweather" = "1"
"sf_allowcl_disableeffects" = "1"
"sf_enable_mapbrowser" = "1"
"sf_mapbloom" = "1" ( def. "0" )
"sf_start_time" = ""
"sf_skybox" = "1"
"sf_debugcompatibility" = "1" ( def. "0" )
"sf_sunmoon_yaw" = "135" ( def. "270" )
"sf_enable_mapsupport" = "1"
"sf_lightningbolts" = "1"
"sf_windpush" = "1"
"sf_weatherdebuffs" = "1"
"sf_enablefog" = "1"
"sf_moonphase" = "1"
"sf_moonscale" = "2" ( def. "6" )
"sf_timespeed" = "60"

**Comment by UAVXP** [comment]
I've tested this issue also with all of my addons disabled - no difference

**Comment by UAVXP** [comment]
Also, forgot to mention that Atmos is doing pretty good job at this unlike StormFox, but with some adjustments. I can send my slightly modified version of Atmos to you if you're interested in it

[YouTube video](https://youtu.be/W5cQsdNN0Oo)
The lighting does not bugging out here

**Comment by Nak2** [comment]
Should be fixed in  v1.398
Thanks for pointing out.
