### ISSUE TITLE
ERROR: Trying to derive entity stormfox_xxxx from non existant entity base_gmodentity!

### ISSUE THREAD

**Issue by Parilar** [Nak2/StormFox#6]
Got this error when starting my Server:

ERROR: Trying to derive entity stormfox_streetlight from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_miniclock from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_combinelight from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_streetlight_invisible from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_weekweather from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_weathermonitor from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_digitalclock2 from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox-weathercontroller from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_wiredata from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_parklight_hanging from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_digitalclock from non existant entity base_gmodentity!
ERROR: Trying to derive entity plasma_ball from non existant entity base_gmodentity!
ERROR: Trying to derive entity bolt2 from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_campfire from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_clock-outdoors from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_parklight from non existant entity base_gmodentity!
ERROR: Trying to derive entity stormfox_clock from non existant entity base_gmodentity!

**Comment by Kefta** [comment]
Your gamemode must be sandbox derived.

**Comment by Parilar** [comment]
Oh okay and is there any way to use it with other gamemodes ?

**Comment by Kefta** [comment]
You can define base_gmodentity in your gamemode: https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/entities/base_gmodentity.lua

**Comment by Parilar** [comment]
Sounds good, i want to use this mod with TTT. I just have to add base_gmodentity.lua or do i have to edit a file to load the lua file ?

**Comment by Kefta** [comment]
Just add the file to the ~/terrortown/entities/entities/ folder.

**Comment by Nak2** [comment]
New update removed the base_gmodentity requirement. (Github only atm)
Thanks for pointing it out.
