### ISSUE TITLE
Lights start flashing at Night

### ISSUE THREAD

**Issue by ApertureDevelopment** [Nak2/StormFox#7]
Me and my Admins experience some problems at night ( StormFox night )
at Night the map lights are constantly flashing, they are turning on and off repeatedly, but like with Transition. 

I don't know why it happens or what causes it, so I am asking if that is a Bug, or a feature.

Also: awesome work. This is the best weather addon for GMod I have ever seen.

Thanks for reading,
~ApDev

**Comment by Nak2** [comment]
I'm not able to replicate the old problem and the code have changed since then.
If the problem keeps happening, feel free to re-open.
