### ISSUE TITLE
Breathing effect is active even when player is dead.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Nak2/StormFox#8]
Maybe add [ply:Alive()](http://wiki.garrysmod.com/page/Player/Alive) check for breathing effect emitting?

![this is wrong](https://user-images.githubusercontent.com/5104603/34506575-2835df18-f03f-11e7-8351-4bb773ff7d56.png)

**Comment by Kefta** [comment]
Spectators need to breathe too!

**Comment by Nak2** [comment]
Sorry for the slow answer .. fixed in next version.
